### ISSUE TITLE
Howard todo's

### ISSUE THREAD

**Issue by hchiam** [House-on-a-Rock/tjc-scheduling-server#44]
backup notes to self, just in case, or if others need to know:

- [x] are you sure - confirm button red
- [x] "+" spacing left like chrome tabs
- [x] context menu styling
- [x] forms styling (#48)
  - [x] tooltips alignment
  - [x] input box spacing
  - [x] ~input grouping like in that article~ (not doing for the 3 forms - very simple and no clear grouping)
  - [x] confirm button should have colour
- [x] expandable (#49)
  - [x] columns aligning (might need to put invisible column match chevron size) [UPDATE: I went with custom code for now, since `<Collapse>` interferes with the level of table rows being direct children of the table]
  - [x] <https://material-ui.com/components/tables/#collapsible-table>

**Comment by hchiam** [comment]
merged both PRs in just now before they get stale or before any new changes cause merge conflicts while i'm away
